#!/bin/bash

# ========================================================
# FUNCTIONAL OVERVIEW
# ========================================================
# Collects files from subfolders and copies them to a 
# flat destination directory using parent folder names.

# Optimized for torrent distribution preparation.
# ========================================================

if [ $# -ne 2 ]; then
    echo "This command requires exactly two arguments: filename suffix - pattern for match + output dir path."
    exit 1
fi

EXT="$1"

# OUTPUT_DIR="$2"

OUTPUT_DIR="${2%/}"
if [ ! -d "$OUTPUT_DIR" ]; then
    echo "Error: Output directory '$OUTPUT_DIR' does not exist."
    exit 1
fi

for dir in */; do
    FILENAME="${dir%/}"
    for file in "$dir"*."$EXT"; do
        if [ -f "$file" ]; then
		cp "$file" "$OUTPUT_DIR/$FILENAME.$EXT"
        fi
    done
done
