#!/usr/bin/env python3

import os
import requests
import sys
from datetime import datetime
from time import sleep


def get_weather_icon():
    try:
        api_key = os.environ.get('OWM_API_KEY')
        city = os.environ.get('OWM_CITY')

        if not api_key or not city:
            raise ValueError("Проверьте OWM_API_KEY и OWM_CITY в .zshrc")

        url = (
            "http://api.openweathermap.org/data/2.5/"
            f"weather?q={city}&appid={api_key}&units=metric"
        )

        retries = 3
        timeout = 30

        for attempt in range(retries):
            try:
                response = requests.get(url, timeout=timeout)
                response.raise_for_status()
                data = response.json()

                # Checking day/night
                current_time = datetime.now().timestamp()
                is_day = (data['sys']['sunrise'] <
                          current_time <
                          data['sys']['sunset'])

                # Fetching weather type
                weather_main = data['weather'][0]['main']

                icons = {
                    'Clear': '☀️' if is_day else '🌙',
                    'Clouds': '☁️',
                    'Rain': '🌧️',
                    'Drizzle': '🌦️',
                    'Thunderstorm': '⛈️',
                    'Snow': '❄️',
                    'Mist': '🌫️',
                    'Fog': '🌫️'
                }

                # Default icon (unknown weather)
                return icons.get(weather_main, '🌀')

            except requests.exceptions.Timeout:
                if attempt < retries - 1:
                    sleep(5)
                    continue
                raise

    except Exception as e:
        print(f"Ошибка: {e}", file=sys.stderr)
        return "E"


if __name__ == "__main__":
    print(get_weather_icon())
